language: php

php:
  - 7.1

matrix:
    allow_failures:
        - php: 5.6

install: travis_retry composer update --no-interaction --prefer-source

matrix:

    allow_failures:
        - php: 7.1

install: travis_retry composer update --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_success:
    - travis_retry php vendor/bin/coveralls
    # or enable logging
    - travis_retry php vendor/bin/coveralls -v