<?php
use Zend\Session\Container;
use Zend\Session\SessionManager;

$sessionManager = new SessionManager();
$sessionContainer = new Container('ContainerNamespace', $sessionManager);
$title = 'Users';
$this->headTitle($title);
$count = 1;
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('user', ['action' => 'add']) ?>" class="btn btn-primary">Add new user</a>
</p>

	<?php
	if (isset($sessionContainer->first_name)) {?>
		<h1><strong> Hello, <?= $sessionContainer->first_name ?></strong> </h1>
	<?php }

    if (isset($sessionContainer->first_name)) {
        $firstName = $sessionContainer->first_name;?>
        <div class="alert alert-success">
          <strong>Success!</strong> Welcome <?= $firstName; ?>, you have been added to our list of users. The list below contains other users.
        </div>
    <?php
        unset($sessionContainer->first_name);
    } if (isset($sessionContainer->success)) {
		$message = $sessionContainer->success;?>
		<div class="alert alert-success">
		  <strong>Success!</strong> <?= $message; ?>
		</div>
	<?php
		unset($sessionContainer->success);
	} if (isset($sessionContainer->failure)) {
		$message = $sessionContainer->failure;?>
		<div class="alert alert-danger">
		  <strong>Oops!</strong> <?= $message; ?>
		</div>
	<?php
		unset($sessionContainer->failure);
	} if (isset($sessionContainer->update_first_name)) {
        $firstName = $sessionContainer->update_first_name;?>
        <div class="alert alert-success">
          <strong>Success!</strong> <?= $firstName; ?> has been updated successfully
        </div>
    <?php
        unset($sessionContainer->update_first_name);
    }
?>

<table id="example" class="table">
<thead>
<tr>
    <th>S/N</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>&nbsp;</th>
</tr>
</thead>
<tbody>
<?php foreach ($users as $user) : ?>
    <tr>
        <td><?= $count++ ?></td>
        <td><?= $this->escapeHtml($user->first_name) ?></td>
        <td><?= $this->escapeHtml($user->last_name) ?></td>
        <td><?= $this->escapeHtml($user->email) ?></td>
        <td>
            <a href="<?= $this->url('user', ['action' => 'edit', 'id' => $user->id]) ?>" title="Edit <?= $user->first_name . " " . $user->last_name ?>">Edit</a>
            <a href="#" class="delete-user" data-id="<?= $user->id ?>" title="Delete <?= $user->first_name . " " . $user->last_name ?>" >Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</tbody>
</table>
